import "./globals.css";
import { Poppins, Libre_Baskerville } from "next/font/google";

import Header from "@/components/Header";
import Footer from "@/components/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
  variable: "--font-poppins",
});
const libre_baskerville = Libre_Baskerville({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
  variable: "--font-libre-baskerville",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${libre_baskerville.variable}`}
    >
      <body className="font-popp flex flex-col min-h-screen bg-brand-beige-10">
        <Header />
        <main className="flex-1 p-4 mx-auto lg:max-w-5xl">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
